apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.NODE_ENV }}
        - name: PORT
          value: {{ .Values.backend.PORT }}
        - name: MONGODB_URI
          value: {{ .Values.backend.MONGODB_URI }}
        - name: JWT_SECRET
          value: {{ .Values.backend.JWT_SECRET }}
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: chat-app-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: chat-app-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: chat-app-secrets
              key: CLOUDINARY_API_SECRET

