apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: {{ .Values.frontend.NODE_ENV }}

