apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 300Mi
  hostPath:
    path: /data