apiVersion: v1
kind: Secret
metadata:
 name: chat-app-secrets
 namespace: chat-app
type: Opaque
data:
 CLOUDINARY_CLOUD_NAME: ZG9iYXloejdw
 CLOUDINARY_API_KEY: MTc5MTI3NzU2NjYxODkx
 CLOUDINARY_API_SECRET: cC1SMDg4RDFwVi1WS1Vub2pjZklXVWVhWjNN